name: Docs CI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          uv --version
      - name: Install dependencies
        run: |
          uv sync --extra dev
      - name: Build docs
        run: |
          uv run make -C docs html
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
